version: "3"

tasks:
  default:
    cmds:
      - /Users/carlosamaral/.local/bin/protoc --proto_path=proto proto/*.proto --go_out=gen/
      - /Users/carlosamaral/.local/bin/protoc --proto_path=proto proto/*.proto --go-grpc_out=gen/
  
  clean:
   cmds:
    - rm gen/proto/*.go