package common

const (
	CREATE_OCCURRENCE_RABBIT_MSG_TYPE = "CREATE_OCCURRENCE"
	ACCEPT_OCCURRENCE_RABBIT_MSG_TYPE = "ACCEPT_OCCURRENCE"
	CANCEL_OCCURRENCE_RABBIT_MSG_TYPE = "CANCEL_OCCURRENCE"
	FINISH_OCCURRENCE_RABBIT_MSG_TYPE = "FINISH_OCCURRENCE"
)
